## Predicting Price of House using KNearestNeighbour Regressor


In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

In [2]:
data = pd.read_csv("house_rental_data.csv.txt",sep=",")
data.head()

Unnamed: 0      Sqft  Floor  TotalFloor  Bedroom  Living.Room  Bathroom  \
0           1  1177.698      2           7        2            2         2   
1           2  2134.800      5           7        4            2         2   
2           3  1138.560      5           7        2            2         1   
3           4  1458.780      2           7        3            2         2   
4           5   967.776     11          14        3            2         2   

   Price  
0  62000  
1  78000  
2  58000  
3  45000  
4  45000

In [3]:
data.shape

(645, 8)

In [4]:
data.isnull().sum()

Unnamed: 0     0
Sqft           0
Floor          0
TotalFloor     0
Bedroom        0
Living.Room    0
Bathroom       0
Price          0
dtype: int64

In [10]:
dic = {'Unnamed: 0':'id'}

In [11]:
data = data.rename(dic,axis = 1)
data.head()

id      Sqft  Floor  TotalFloor  Bedroom  Living.Room  Bathroom  Price
0   1  1177.698      2           7        2            2         2  62000
1   2  2134.800      5           7        4            2         2  78000
2   3  1138.560      5           7        2            2         1  58000
3   4  1458.780      2           7        3            2         2  45000
4   5   967.776     11          14        3            2         2  45000

In [12]:
data = data.set_index('id')
data.head()

Sqft  Floor  TotalFloor  Bedroom  Living.Room  Bathroom  Price
id                                                                    
1   1177.698      2           7        2            2         2  62000
2   2134.800      5           7        4            2         2  78000
3   1138.560      5           7        2            2         1  58000
4   1458.780      2           7        3            2         2  45000
5    967.776     11          14        3            2         2  45000

In [13]:
x = data.drop('Price',axis = 1)
y = data['Price']

In [14]:
x

Sqft  Floor  TotalFloor  Bedroom  Living.Room  Bathroom
id                                                              
1    1177.698      2           7        2            2         2
2    2134.800      5           7        4            2         2
3    1138.560      5           7        2            2         1
4    1458.780      2           7        3            2         2
5     967.776     11          14        3            2         2
..        ...    ...         ...      ...          ...       ...
644  1359.156      7          15        3            2         2
645   377.148      4          10        1            1         1
646   740.064     13          14        1            1         1
647  1707.840      3          14        3            2         2
648  1376.946      6           7        3            2         1

[645 rows x 6 columns]

In [15]:
y

id
1      62000
2      78000
3      58000
4      45000
5      45000
       ...  
644    45000
645    24800
646    45000
647    65000
648    36000
Name: Price, Length: 645, dtype: int64

In [17]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.2,random_state = 42)

In [18]:
x_train

Sqft  Floor  TotalFloor  Bedroom  Living.Room  Bathroom
id                                                              
519  1487.244      6           7        3            1         2
30    853.920      6           7        2            1         1
277  1138.560      4           5        3            2         2
580   693.810      2           7        1            1         1
438  2910.444      4           7        3            2         3
..        ...    ...         ...      ...          ...       ...
72   1284.438      6          12        3            2         2
108  3202.200     12          12        5            3         3
273  1366.272      4          11        4            2         2
439  3010.068      4          11        3            2         2
104  2938.908      2          25        4            2         2

[516 rows x 6 columns]

In [19]:
x_test

Sqft  Floor  TotalFloor  Bedroom  Living.Room  Bathroom
id                                                              
636  1099.422      2           7        4            2         2
596  1102.980      2           4        2            2         2
603  1458.780     21          27        3            2         2
295   761.412      8          13        1            1         1
73   1892.856      2           7        4            2         3
..        ...    ...         ...      ...          ...       ...
517   843.246      2          18        1            1         1
635   996.240      3           5        3            1         1
218  1743.420      3          12        3            2         2
612   711.600      8          12        1            2         1
137  1921.320      4           7        4            2         2

[129 rows x 6 columns]

In [21]:
from sklearn.neighbors import KNeighborsRegressor
knr = KNeighborsRegressor()
knr

KNeighborsRegressor()

In [22]:
knr.fit(x_train,y_train)

KNeighborsRegressor()

In [23]:
y_pred = knr.predict(x_test)
y_pred

array([ 41400. ,  41400. ,  60200. ,  44000. ,  92599.8,  66000. ,
        87600. ,  86200. ,  67600. ,  34599.8,  59177.6,  37800. ,
        43400. ,  42200. ,  23277.6,  73800. ,  60624. ,  38900. ,
        42600. ,  33200. ,  58400. ,  48400. ,  40600. , 201000. ,
       201200. ,  49500. ,  61600. ,  37360. ,  37600. ,  34800. ,
        44520. ,  82200. ,  82999.8,  33000. ,  37800. ,  57560. ,
        97000. ,  64400. ,  61100. ,  68000. ,  66600. , 153800. ,
        73800. ,  97000. ,  40739.8,  33000. ,  33300. ,  42405.4,
        68520. ,  29419.8,  51599.8,  67600. , 197200. ,  84000. ,
        64400. ,  67600. , 106999.8,  38200. ,  79599.8,  74200. ,
        92599.8, 129599.8,  87600. ,  60000. ,  98199.8,  38800. ,
        34099.8,  36606.4,  23277.6,  60200. ,  29800. ,  34099.8,
        31000.4,  23277.6,  70599.8,  31766.4,  77999.6,  47600. ,
        45800. ,  45000. ,  70599.8,  88799.8,  43400. ,  32700.4,
        40739.8,  25900. , 129599.8,  90000. ,  37800. ,  4120

In [24]:
from sklearn.metrics import r2_score
r2_score(y_test,y_pred)

0.7028529270810101

In [26]:
from sklearn.neighbors import KNeighborsRegressor
knr_3 = KNeighborsRegressor(n_neighbors = 3,p=1)
knr_3

KNeighborsRegressor(n_neighbors=3, p=1)

In [27]:
knr_3.fit(x_train,y_train)

KNeighborsRegressor(n_neighbors=3, p=1)

In [28]:
y_pred3 = knr_3.predict(x_test)
y_pred3

array([ 50000.        ,  30666.66666667,  52000.        ,  41666.66666667,
        87666.33333333,  66666.66666667,  79333.33333333,  74333.33333333,
        66666.66666667,  36333.33333333,  49000.        ,  33000.        ,
        44333.33333333,  35333.33333333,  26166.66666667,  77666.66666667,
        69373.33333333,  33166.66666667,  44666.66666667,  30666.66666667,
        71333.33333333,  49000.        ,  41000.        , 201666.66666667,
       200000.        ,  47666.66666667,  52666.66666667,  32266.66666667,
        36166.66666667,  32666.66666667,  47200.        ,  81000.        ,
        95000.        ,  35333.33333333,  33000.        ,  64333.33333333,
        98333.33333333,  60666.66666667,  43833.33333333,  61333.33333333,
        66666.66666667, 143000.        ,  67666.66666667,  98333.33333333,
        40666.66666667,  33000.        ,  32000.        ,  46666.33333333,
        62200.        ,  25699.66666667,  46666.66666667,  66666.66666667,
       193333.33333333,  

In [29]:
pre2 = r2_score(y_test,y_pred3)
pre2

0.7100425321768584

In [30]:
from sklearn.neighbors import KNeighborsRegressor
knr_9 = KNeighborsRegressor(n_neighbors = 9,p=1)
knr_9

KNeighborsRegressor(n_neighbors=9, p=1)

In [31]:
knr_9.fit(x_train,y_train)

KNeighborsRegressor(n_neighbors=9, p=1)

In [32]:
y_pred9 = knr_9.predict(x_test)
y_pred9

array([ 40755.55555556,  40755.55555556,  56666.66666667,  42333.33333333,
        88666.44444444,  62432.        ,  88222.11111111,  88999.66666667,
        70555.55555556,  40388.77777778,  58487.55555556,  38543.11111111,
        41555.55555556,  41444.44444444,  27487.55555556,  68888.88888889,
        55235.55555556,  37277.77777778,  44888.88888889,  36111.11111111,
        50333.33333333,  44444.44444444,  39777.77777778, 181555.55555556,
       172111.11111111,  46277.77777778,  61333.33333333,  35533.33333333,
        32222.22222222,  39888.88888889,  45844.44444444,  92333.22222222,
        84999.66666667,  49555.55555556,  37987.55555556,  66977.77777778,
        92555.55555556,  65555.55555556,  69944.33333333,  69888.77777778,
        62000.        , 157666.66666667,  85444.44444444,  92555.55555556,
        50855.33333333,  50333.33333333,  35388.77777778,  36428.77777778,
        60600.        ,  31233.22222222,  48666.55555556,  70555.55555556,
       172111.11111111,  

In [33]:
pre3 = r2_score(y_test,y_pred9)
pre3

0.7345883950626196

In [34]:
from sklearn.neighbors import KNeighborsRegressor
knr_9 = KNeighborsRegressor(n_neighbors = 9)
knr_9

KNeighborsRegressor(n_neighbors=9)

In [35]:
knr_9.fit(x_train,y_train)

KNeighborsRegressor(n_neighbors=9)

In [36]:
y_pred9 = knr_9.predict(x_test)
y_pred9

array([ 41755.55555556,  40755.55555556,  56111.        ,  42888.88888889,
        88666.44444444,  62432.        ,  88999.88888889,  95444.22222222,
        70555.55555556,  33722.11111111,  58487.55555556,  38543.11111111,
        41555.55555556,  41444.44444444,  27487.55555556,  82111.11111111,
        55235.55555556,  37277.77777778,  44888.88888889,  36111.11111111,
        50888.88888889,  47987.55555556,  39777.77777778, 181555.55555556,
       172111.11111111,  46277.77777778,  61333.33333333,  37200.        ,
        32222.22222222,  39209.77777778,  45844.44444444,  92333.22222222,
        76111.        ,  50333.33333333,  38320.88888889,  62511.11111111,
        92555.55555556,  66111.11111111,  68277.66666667,  69888.77777778,
        59444.44444444, 157666.66666667,  85444.44444444,  92555.55555556,
        46398.55555556,  50333.33333333,  35388.77777778,  42291.77777778,
        60822.22222222,  33899.88888889,  48666.55555556,  70555.55555556,
       172111.11111111,  

In [37]:
pre3 = r2_score(y_test,y_pred9)
pre3

0.7278512066199561