## Cluster similar Houses


In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

In [2]:
data = pd.read_csv("house_rental_data.csv.txt",sep=",")
data.head()

Unnamed: 0      Sqft  Floor  TotalFloor  Bedroom  Living.Room  Bathroom  \
0           1  1177.698      2           7        2            2         2   
1           2  2134.800      5           7        4            2         2   
2           3  1138.560      5           7        2            2         1   
3           4  1458.780      2           7        3            2         2   
4           5   967.776     11          14        3            2         2   

   Price  
0  62000  
1  78000  
2  58000  
3  45000  
4  45000

In [3]:
dic = {'Unnamed: 0':'Id'}
data = data.rename(dic,axis = 1)
data.head()

Id      Sqft  Floor  TotalFloor  Bedroom  Living.Room  Bathroom  Price
0   1  1177.698      2           7        2            2         2  62000
1   2  2134.800      5           7        4            2         2  78000
2   3  1138.560      5           7        2            2         1  58000
3   4  1458.780      2           7        3            2         2  45000
4   5   967.776     11          14        3            2         2  45000

In [4]:
data = data.set_index('Id')
data.head()

Sqft  Floor  TotalFloor  Bedroom  Living.Room  Bathroom  Price
Id                                                                    
1   1177.698      2           7        2            2         2  62000
2   2134.800      5           7        4            2         2  78000
3   1138.560      5           7        2            2         1  58000
4   1458.780      2           7        3            2         2  45000
5    967.776     11          14        3            2         2  45000

In [5]:
data.shape

(645, 7)

In [6]:
data.isnull().sum()

Sqft           0
Floor          0
TotalFloor     0
Bedroom        0
Living.Room    0
Bathroom       0
Price          0
dtype: int64

In [7]:
x = data.drop('Price',axis = 1)
y = data['Price']

In [8]:
x

Sqft  Floor  TotalFloor  Bedroom  Living.Room  Bathroom
Id                                                              
1    1177.698      2           7        2            2         2
2    2134.800      5           7        4            2         2
3    1138.560      5           7        2            2         1
4    1458.780      2           7        3            2         2
5     967.776     11          14        3            2         2
..        ...    ...         ...      ...          ...       ...
644  1359.156      7          15        3            2         2
645   377.148      4          10        1            1         1
646   740.064     13          14        1            1         1
647  1707.840      3          14        3            2         2
648  1376.946      6           7        3            2         1

[645 rows x 6 columns]

## KMeans Clustering

In [9]:
from sklearn.cluster import KMeans
kmeans = KMeans()
kmeans

KMeans()

## Feature Scaling

In [10]:
from sklearn.preprocessing import MinMaxScaler
mms = MinMaxScaler()
mms

MinMaxScaler()

In [11]:
x = mms.fit_transform(x)
x

array([[0.14886731, 0.04761905, 0.16216216, 0.16666667, 0.5       ,
        0.4       ],
       [0.32297735, 0.19047619, 0.16216216, 0.5       , 0.5       ,
        0.4       ],
       [0.14174757, 0.19047619, 0.16216216, 0.16666667, 0.5       ,
        0.2       ],
       ...,
       [0.06925566, 0.57142857, 0.35135135, 0.        , 0.25      ,
        0.2       ],
       [0.24530744, 0.0952381 , 0.35135135, 0.33333333, 0.5       ,
        0.4       ],
       [0.18511327, 0.23809524, 0.16216216, 0.33333333, 0.5       ,
        0.2       ]])

In [12]:
kmeans.fit(x)

KMeans()

In [13]:
kmeans.cluster_centers_

array([[0.23348828, 0.12756133, 0.15102375, 0.41111111, 0.49393939,
        0.4169697 ],
       [0.07055016, 0.15894466, 0.20708546, 0.09009009, 0.23986486,
        0.21351351],
       [0.42473031, 0.78571429, 0.54617117, 0.48611111, 0.53125   ,
        0.56666667],
       [0.12414583, 0.15929204, 0.20330065, 0.17551622, 0.50221239,
        0.25663717],
       [0.27603346, 0.15768194, 0.3763386 , 0.39779874, 0.48820755,
        0.4       ],
       [0.23816155, 0.42135642, 0.34889435, 0.34680135, 0.48989899,
        0.4040404 ],
       [0.56662445, 0.19875776, 0.28319624, 0.48550725, 0.55434783,
        0.68695652],
       [0.07910648, 0.46457607, 0.35464733, 0.09349593, 0.26219512,
        0.2       ]])

In [19]:
cluster_label = kmeans.fit_predict(x)
cluster_label

array([4, 1, 4, 1, 7, 7, 4, 2, 7, 1, 2, 2, 7, 4, 7, 3, 4, 2, 3, 4, 0, 3,
       4, 1, 0, 7, 0, 0, 2, 2, 7, 5, 7, 4, 4, 2, 4, 1, 0, 4, 0, 5, 1, 1,
       3, 1, 4, 3, 0, 2, 3, 4, 4, 4, 6, 1, 2, 7, 4, 1, 2, 1, 1, 1, 2, 2,
       4, 2, 2, 1, 5, 1, 1, 4, 4, 1, 3, 3, 3, 4, 1, 2, 4, 4, 1, 1, 6, 3,
       1, 3, 3, 1, 4, 1, 1, 1, 3, 1, 7, 1, 1, 3, 3, 6, 3, 1, 0, 4, 3, 7,
       3, 1, 1, 7, 7, 1, 6, 2, 5, 4, 5, 7, 1, 1, 7, 4, 2, 3, 1, 5, 1, 1,
       0, 4, 3, 1, 2, 1, 1, 7, 0, 1, 4, 1, 1, 5, 3, 3, 1, 3, 7, 1, 1, 5,
       7, 4, 5, 1, 1, 1, 1, 5, 4, 6, 1, 7, 3, 3, 4, 5, 1, 7, 1, 7, 4, 0,
       3, 1, 4, 1, 7, 4, 6, 2, 2, 1, 1, 1, 1, 2, 4, 2, 7, 7, 1, 7, 7, 5,
       4, 1, 7, 7, 1, 2, 3, 4, 7, 4, 7, 1, 7, 2, 3, 4, 1, 1, 1, 7, 2, 0,
       4, 7, 3, 5, 3, 4, 2, 4, 6, 7, 1, 4, 3, 1, 3, 2, 1, 1, 2, 1, 5, 7,
       6, 0, 7, 4, 3, 5, 6, 1, 3, 3, 7, 7, 1, 2, 2, 1, 6, 4, 7, 5, 4, 1,
       1, 4, 2, 4, 1, 7, 1, 1, 5, 2, 1, 1, 4, 3, 4, 2, 5, 1, 3, 5, 6, 5,
       7, 7, 5, 3, 4, 5, 7, 1, 1, 7, 3, 3, 0, 3, 1,

In [35]:
df = pd.DataFrame(cluster_label, columns= ['Cluster'])

In [37]:
df = mms.fit_transform(df)
df

array([[0.57142857],
       [0.14285714],
       [0.57142857],
       [0.14285714],
       [1.        ],
       [1.        ],
       [0.57142857],
       [0.28571429],
       [1.        ],
       [0.14285714],
       [0.28571429],
       [0.28571429],
       [1.        ],
       [0.57142857],
       [1.        ],
       [0.42857143],
       [0.57142857],
       [0.28571429],
       [0.42857143],
       [0.57142857],
       [0.        ],
       [0.42857143],
       [0.57142857],
       [0.14285714],
       [0.        ],
       [1.        ],
       [0.        ],
       [0.        ],
       [0.28571429],
       [0.28571429],
       [1.        ],
       [0.71428571],
       [1.        ],
       [0.57142857],
       [0.57142857],
       [0.28571429],
       [0.57142857],
       [0.14285714],
       [0.        ],
       [0.57142857],
       [0.        ],
       [0.71428571],
       [0.14285714],
       [0.14285714],
       [0.42857143],
       [0.14285714],
       [0.57142857],
       [0.428